image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  # TODO Start: [Student] Set as only master
  only:
    - master
  # TODO End: [Student] Set as only master

unit-test:
  # TODO Start: [Student] Set job image
  image: python:3.9
  # TODO End: [Student] Set job image
  stage: test
  before_script:
    # TODO Start: [Student] Install dependencies
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
    # TODO End: [Student] Install dependencies
  script:
    # TODO Start: [Student] Migrate and run tests
    - python3 manage.py makemigrations board
    - python3 manage.py migrate
    - sh ./test.sh
    # TODO End: [Student] Migrate and run tests
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

deploy:
  stage: deploy
  script:
    - export DEPLOY_ENV=$GITLAB_USER_LOGIN
    - deployer dyno replace backend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  # TODO Start: [Student] Set as only master
  only:
    - master
  # TODO End: [Student] Set as only master