# Generated by Django 4.1.3 on 2023-04-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_function_string'),
        ('Asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='children',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetclass',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asset.assetclass'),
        ),
    ]
