# Generated by Django 4.1.3 on 2023-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0002_assetclass_children_assetclass_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='property',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
