# Generated by Django 4.1.3 on 2023-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='function_string',
            field=models.CharField(default='0000000000000000000011', max_length=50),
            preserve_default=False,
        ),
    ]
