# Generated by Django 4.1.3 on 2023-04-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0010_alter_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="path",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Is_Locked",
            field=models.BooleanField(default=False),
        ),
    ]
