# Generated by Django 4.1.3 on 2023-04-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0011_department_path_user_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="entity",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="User.entity"
            ),
        ),
    ]
